In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df = pd.DataFrame(pd.read_csv("C:/Users/divya/AIML/Cr-02-ML_AZ/MLAZ_Course/datasets/Data1.csv"))

In [3]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
df.columns

Index(['AT', 'V', 'AP', 'RH', 'PE'], dtype='object')

#DECISION TREE REGRESSION

In [11]:
X_dr = df.drop("PE", axis=1).values

In [13]:
X_dr

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [14]:
y_dr = df["PE"].values
y_dr

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [15]:
from sklearn.model_selection import train_test_split

In [19]:
 X_train_dr, X_test_dr, y_train_dr, y_test_dr = train_test_split(X_dr, y_dr, test_size=0.2, random_state=0)

In [20]:
from sklearn.tree import DecisionTreeRegressor

In [21]:
regressor = DecisionTreeRegressor(random_state=0)

In [22]:
regressor.fit(X_train_dr, y_train_dr)

DecisionTreeRegressor(random_state=0)

In [28]:
y_pred_dr = regressor.predict(X_test_dr)

In [29]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_dr.reshape(len(y_pred_dr),1), y_test_dr.reshape(len(y_test),1)),1))


[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


In [40]:
from sklearn.metrics import r2_score
r2_score(y_test_dr, y_pred_dr)

0.922905874177941

#MULTIPLE LINEAR REGRESSION

In [41]:
X_mlr = df.drop("PE", axis=1).values
X_mlr

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [44]:
y_mlr = df["PE"].values
y_mlr

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [45]:
X_train_mlr, X_test_mlr, y_train_mlr, y_test_mlr = train_test_split(X_mlr, y_mlr, test_size=0.2, random_state=0)

In [46]:
from sklearn.linear_model import LinearRegression

linerRegressor = LinearRegression()

In [47]:
linerRegressor.fit(X_train_mlr, y_train_mlr)

LinearRegression()

In [48]:
y_pred_mlr = linerRegressor.predict(X_test_mlr)

In [49]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_mlr.reshape(len(y_pred_mlr),1), y_test_mlr.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [50]:
r2_score(y_test_mlr, y_pred_mlr)

0.9325315554761303

#POLYNOMIAL REGRESSION

In [54]:
X_pr = df.drop("PE", axis=1).values
y_pr = df["PE"].values

In [55]:
X_train_pr, X_test_pr, y_train_pr, y_test_pr = train_test_split(X_pr, y_pr, test_size=0.2, random_state=0)

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [59]:
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train_pr)
linearRegressor = LinearRegression()
linearRegressor.fit(X_poly, y_train)

LinearRegression()

In [61]:
y_pred_pr = linearRegressor.predict(poly_reg.transform(X_test_pr))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_pr.reshape(len(y_pred_pr),1), y_test_pr.reshape(len(y_test_pr),1)),1))

[[434.16 431.23]
 [458.26 460.01]
 [460.72 461.14]
 ...
 [469.49 473.26]
 [438.53 438.  ]
 [461.62 463.28]]


In [62]:
from sklearn.metrics import r2_score
r2_score(y_test_pr, y_pred_pr)

0.9455261541488463

#RANDOM FOREST REGRESSION

In [63]:
X_rfr = df.drop("PE", axis=1).values
y_rfr = df["PE"].values

In [64]:
X_train_rfr, X_test_rfr, y_train_rfr, y_test_rfr = train_test_split(X_rfr, y_rfr, test_size=0.2, random_state=0)

In [66]:
from sklearn.ensemble import RandomForestRegressor
rfRegressor = RandomForestRegressor()

In [67]:
rfRegressor.fit(X_train_rfr, y_train_rfr)

RandomForestRegressor()

In [69]:
rfrpredictor = rfRegressor.predict(X_test_rfr)

In [72]:
np.set_printoptions(precision=2)
print(np.concatenate((rfrpredictor.reshape(len(rfrpredictor),1), y_test_rfr.reshape(len(y_test_rfr),1)),1))

[[433.84 431.23]
 [457.51 460.01]
 [463.25 461.14]
 ...
 [469.12 473.26]
 [438.77 438.  ]
 [461.44 463.28]]


In [70]:
r2_score(y_test_rfr, rfrpredictor)

0.9655961492137018

#SUPPORT VECTOR REGRESSION

In [89]:
X_svr = df.drop("PE", axis=1).values
y_svr = df["PE"].values
y_svr = y_svr.reshape(len(y_svr), 1)

In [90]:
X_train_svr, X_test_svr, y_train_svr, y_test_svr = train_test_split(X_svr, y_svr, test_size=0.2, random_state=0)

In [91]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()

X_train_svr = sc_x.fit_transform(X_train_svr)
y_train_svr = sc_y.fit_transform(y_train_svr)

In [92]:
from sklearn.svm import SVR

In [95]:
svRegressor = SVR(kernel = 'rbf')
svRegressor.fit(X_train_svr, y_train_svr)

C:\Users\divya\anaconda3\envs\conda_new_env\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [97]:
y_pred_svr = sc_y.inverse_transform(svRegressor.predict(sc_x.transform(X_test_svr)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_svr.reshape(len(y_pred_svr),1), y_test.reshape(len(y_test_svr),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [98]:
from sklearn.metrics import r2_score
r2_score(y_test_svr, y_pred_svr)

0.948078404998626