In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
df = pd.DataFrame(pd.read_csv("C:/Users/divya/AIML/Cr-02-ML_AZ/MLAZ_Course/datasets/ClassificationData.csv"))

In [2]:
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [4]:
df.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.830000e+02       683.000000               683.000000   
mean         1.076720e+06         4.442167                 3.150805   
std          6.206440e+05         2.820761                 3.065145   
min          6.337500e+04         1.000000                 1.000000   
25%          8.776170e+05         2.000000                 1.000000   
50%          1.171795e+06         4.000000                 1.000000   
75%          1.238705e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   683.000000   683.000000       683.000000   
mean                      3.234261     3.544656         3.445095   
std                       2.223085     3.643857         2.449697   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     6.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses       Class  
count       683.000000  683.000000  683.000000  
mean          2.869693    1.603221    2.699854  
std           3.052666    1.732674    0.954592  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [7]:
X = df.drop('Class', axis=1).values
y = df['Class'].values

In [8]:
print(y)

[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2 2 2 4 2 2
 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4
 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 4 2 4 4 4 2
 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 4 4 2 2 2 4 4 4 2 4 2 4 2 2
 2 2 2 2 2 2 2 2 2 2 4 2 

In [11]:
print(X)

[[1000025       5       1 ...       3       1       1]
 [1002945       5       4 ...       3       2       1]
 [1015425       3       1 ...       3       1       1]
 ...
 [ 888820       5      10 ...       8      10       2]
 [ 897471       4       8 ...      10       6       1]
 [ 897471       4       8 ...      10       4       1]]


In [13]:
#splitting dataset into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [15]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [16]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# 1. Decision Tree Classification

In [63]:
from sklearn.tree import DecisionTreeClassifier
dcClassfier = DecisionTreeClassifier(random_state=0, criterion='entropy')

In [64]:
dcClassfier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [65]:
y_dc_pred = dcClassfier.predict(X_test)

In [66]:
print(classification_report(y_test, y_dc_pred))
print()
print(confusion_matrix(y_test, y_dc_pred))
print()
print(accuracy_score(y_test, y_dc_pred))

              precision    recall  f1-score   support

           2       0.97      0.96      0.97       107
           4       0.94      0.95      0.95        64

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171


[[103   4]
 [  3  61]]

0.9590643274853801


# 2. KNN Classification

In [33]:
from sklearn.neighbors import KNeighborsClassifier
ngClassifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)

In [34]:
ngClassifier.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
y_knn_pred = ngClassifier.predict(X_test)

In [37]:
print(classification_report(y_test, y_knn_pred))
print()
print(confusion_matrix(y_test, y_knn_pred))
print()
print(accuracy_score(y_test, y_knn_pred))

              precision    recall  f1-score   support

           2       0.95      0.96      0.96       107
           4       0.94      0.92      0.93        64

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171


[[103   4]
 [  5  59]]

0.9473684210526315


# 3. Kernel SVM

In [40]:
from sklearn.svm import SVC
ksvm_Classifier = SVC(kernel='rbf', random_state=0)

In [41]:
ksvm_Classifier.fit(X_train, y_train)

SVC(random_state=0)

In [42]:
y_ksvm_pred = ksvm_Classifier.predict(X_test)

In [43]:
print(classification_report(y_test, y_ksvm_pred))
print()
print(confusion_matrix(y_test, y_ksvm_pred))
print()
print(accuracy_score(y_test, y_ksvm_pred))

              precision    recall  f1-score   support

           2       0.97      0.95      0.96       107
           4       0.92      0.95      0.94        64

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171


[[102   5]
 [  3  61]]

0.9532163742690059


# 4. Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression
lr_Classifier = LogisticRegression()

In [45]:
lr_Classifier.fit(X_train, y_train)

LogisticRegression()

In [46]:
y_lr_pred = lr_Classifier.predict(X_test)

In [47]:
print(classification_report(y_test, y_lr_pred))
print()
print(confusion_matrix(y_test, y_lr_pred))
print()
print(accuracy_score(y_test, y_lr_pred))

              precision    recall  f1-score   support

           2       0.95      0.96      0.96       107
           4       0.94      0.92      0.93        64

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171


[[103   4]
 [  5  59]]

0.9473684210526315


# 5. Naive Bayes

In [48]:
from sklearn.naive_bayes import GaussianNB
gnb_classifier = GaussianNB()

In [50]:
gnb_classifier.fit(X_train, y_train)

GaussianNB()

In [51]:
y_gnb_pred = gnb_classifier.predict(X_test)

In [52]:
print(classification_report(y_test, y_gnb_pred))
print()
print(confusion_matrix(y_test, y_gnb_pred))
print()
print(accuracy_score(y_test, y_gnb_pred))

              precision    recall  f1-score   support

           2       0.98      0.93      0.95       107
           4       0.89      0.97      0.93        64

    accuracy                           0.94       171
   macro avg       0.93      0.95      0.94       171
weighted avg       0.94      0.94      0.94       171


[[99  8]
 [ 2 62]]

0.9415204678362573


# 6. Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier
rnd_Classifier = RandomForestClassifier(n_estimators=10, criterion = 'entropy', random_state = 0)

In [55]:
rnd_Classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [56]:
y_rnd_pred = rnd_Classifier.predict(X_test)

In [57]:
print(classification_report(y_test, y_rnd_pred))
print()
print(confusion_matrix(y_test, y_rnd_pred))
print()
print(accuracy_score(y_test, y_rnd_pred))

              precision    recall  f1-score   support

           2       0.94      0.95      0.95       107
           4       0.92      0.91      0.91        64

    accuracy                           0.94       171
   macro avg       0.93      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171


[[102   5]
 [  6  58]]

0.935672514619883


# 7. SVM

In [58]:
from sklearn.svm import SVC
svc_Classifier = SVC(kernel='linear', random_state=0)

In [59]:
svc_Classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [60]:
y_svm_pred = svc_Classifier.predict(X_test)

In [61]:
print(classification_report(y_test, y_svm_pred))
print()
print(confusion_matrix(y_test, y_svm_pred))
print()
print(accuracy_score(y_test, y_svm_pred))

              precision    recall  f1-score   support

           2       0.95      0.95      0.95       107
           4       0.92      0.92      0.92        64

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171


[[102   5]
 [  5  59]]

0.9415204678362573


# Result - Optimal Classifier - DECISION TREE CLASSIFICATION - 0.9590643274853801